const { logger } = require('./logger');

function buildEnvContent(answers) {
  const lines = [];

  lines.push('# SecureAuth Configuration (Node.js/Express)');
  lines.push('# Auto-generated by SecureAuth CLI');
  lines.push('');

  lines.push('# ── Server Configuration ──');
  lines.push(`PORT=${answers.port}`);
  lines.push('NODE_ENV=development');
  lines.push('');

  lines.push('# ── JWT Configuration ──');
  lines.push(`JWT_SECRET=${answers.jwtSecret}`);
  lines.push('JWT_ALGORITHM=HS256');
  lines.push('JWT_TEMP_EXPIRY_MINUTES=5');
  lines.push('JWT_FULL_EXPIRY_HOURS=24');
  lines.push('');

  lines.push('# ── Bcrypt Configuration ──');
  lines.push('BCRYPT_ROUNDS=12');
  lines.push('');

  lines.push('# ── TOTP Configuration ──');
  lines.push(`TOTP_ISSUER=${answers.projectName || 'SecureAuth-App'}`);
  lines.push('TOTP_WINDOW=1');
  lines.push('');

  if (answers.features && answers.features.includes('accountLockout')) {
    lines.push('# ── Account Lockout ──');
    lines.push('INACTIVITY_TIMEOUT_MINUTES=5');
    lines.push('MAX_FAILED_ATTEMPTS=5');
    lines.push('LOCKOUT_DURATION_MINUTES=30');
    lines.push('');
  }

  lines.push('# ── Database Configuration ──');
  if (answers.database === 'postgres') {
    lines.push('# For PostgreSQL, provide your connection string below');
    lines.push('# Format: postgresql://user:password@host:5432/database');
    lines.push('DATABASE_URL=postgresql://user:password@localhost:5432/secureauth');
  } else {
    lines.push('# SQLite — local database file (zero config)');
    lines.push('DATABASE_URL=./secureauth.db');
  }
  lines.push('');

  if (answers.features && answers.features.includes('ddos')) {
    lines.push('# ── DDoS Protection Limits ──');
    lines.push('MAX_REQUEST_SIZE=100kb');
    lines.push('MAX_REQUESTS_PER_MINUTE=60');
    lines.push('AUTO_BAN_THRESHOLD=100');
    lines.push('BAN_DURATION_MINUTES=30');
    lines.push('MAX_CONCURRENT_CONNECTIONS=100');
    lines.push('');
  }

  return lines.join('\n');
}

function mergeEnvContent(existingContent, newContent) {
  const existingLines = existingContent.split(/\r?\n/);
  const existingMap = new Map();
  const existingOrder = [];

  for (const line of existingLines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      existingOrder.push({ type: 'raw', line });
      continue;
    }
    const eqIdx = line.indexOf('=');
    if (eqIdx === -1) {
      existingOrder.push({ type: 'raw', line });
      continue;
    }
    const key = line.slice(0, eqIdx).trim();
    existingMap.set(key, line);
    existingOrder.push({ type: 'key', key });
  }

  // Start from existing content (preserve host app settings)
  const result = existingContent.replace(/\s*$/, '');
  const keysPresent = new Set(existingMap.keys());

  const toAppend = [];
  const newLines = newContent.split(/\r?\n/);
  let pendingComment = [];

  for (const line of newLines) {
    const trimmed = line.trim();
    if (!trimmed) {
      pendingComment = [];
      continue;
    }
    if (trimmed.startsWith('#')) {
      pendingComment.push(line);
      continue;
    }
    const eqIdx = line.indexOf('=');
    if (eqIdx === -1) continue;
    const key = line.slice(0, eqIdx).trim();
    if (keysPresent.has(key)) {
      pendingComment = [];
      continue; // keep existing value
    }
    // New key from SecureAuth — append with its section comment if any
    if (pendingComment.length) {
      toAppend.push('');
      toAppend.push(...pendingComment);
      pendingComment = [];
    }
    toAppend.push(line);
    keysPresent.add(key);
  }

  if (toAppend.length === 0) {
    return existingContent;
  }

  return result + '\n' + toAppend.join('\n') + '\n';
}

function writeEnvFile(targetDir, answers) {
  const fs = require('fs');
  const path = require('path');
  const envPath = path.join(targetDir, '.env');

  const newContent = buildEnvContent(answers);

  if (fs.existsSync(envPath)) {
    const existingContent = fs.readFileSync(envPath, 'utf-8');
    const merged = mergeEnvContent(existingContent, newContent);
    if (merged !== existingContent) {
      fs.writeFileSync(envPath, merged, 'utf-8');
      logger.success('.env updated with SecureAuth settings (preserved existing values)');
    } else {
      logger.warn('.env already exists — settings are up to date');
    }
    return true;
  }

  fs.writeFileSync(envPath, newContent, 'utf-8');
  logger.success('.env created with secure defaults');
  return true;
}

module.exports = { writeEnvFile, buildEnvContent };
