const fs = require('fs');
const path = require('path');
const { logger } = require('./logger');

const ENTRY_CANDIDATES = ['server.js', 'app.js', 'index.js'];
const NESTED_ENTRIES = [
  ['backend', 'server.js'],
  ['backend', 'app.js'],
  ['backend', 'index.js'],
  ['src', 'server.js'],
  ['src', 'app.js'],
  ['src', 'index.js']
];
const AUTH_ROUTE_PATTERNS = [
  ['routes', 'auth.js'],
  ['routes', 'authRoutes.js'],
  ['backend', 'routes', 'auth.js'],
  ['backend', 'routes', 'authRoutes.js'],
  ['src', 'routes', 'auth.js'],
  ['src', 'routes', 'authRoutes.js']
];

function findEntryPoint(targetDir) {
  for (const name of ENTRY_CANDIDATES) {
    const p = path.join(targetDir, name);
    if (fs.existsSync(p)) return p;
  }
  for (const parts of NESTED_ENTRIES) {
    const p = path.join(targetDir, ...parts);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

function findAuthRouteFile(targetDir) {
  const entry = findEntryPoint(targetDir);
  if (entry) {
    const content = fs.readFileSync(entry, 'utf-8');
    const regex = /require\(['"](\.?\.?\/[^'"]*(?:auth|login)[^'"]*)['"]\)/i;
    const m = content.match(regex);
    if (m) {
      let routePath = m[1].replace(/\.js$/, '');
      const base = path.dirname(entry);
      for (const ext of ['', '.js']) {
        const full = path.resolve(base, routePath + ext);
        if (fs.existsSync(full)) return full;
      }
    }
  }
  for (const parts of AUTH_ROUTE_PATTERNS) {
    const p = path.join(targetDir, ...parts);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

function detectDatabaseType(targetDir) {
  const pkgPath = path.join(targetDir, 'package.json');
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
      const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
      if ('pg' in allDeps || '@neondatabase/serverless' in allDeps) return 'postgres';
      if ('better-sqlite3' in allDeps || 'sql.js' in allDeps) return 'sqlite';
      if ('mysql2' in allDeps) return 'mysql';
    } catch {}
  }
  const entry = findEntryPoint(targetDir);
  if (entry) {
    try {
      const content = fs.readFileSync(entry, 'utf-8');
      if (/require\(['"](pg|@neondatabase\/serverless)['"]\)/.test(content)) return 'postgres';
      if (/require\(['"]better-sqlite3['"]\)/.test(content)) return 'sqlite';
      if (/require\(['"]mysql2['"]\)/.test(content)) return 'mysql';
    } catch {}
  }
  return 'sqlite';
}

function isAlreadyPatched(content) {
  return /secureauth\/accountLockout|createAccountLockout|checkAccountLockout/.test(content) ||
    /MAX_FAILED_ATTEMPTS/.test(content) ||
    /failed_login_attempts/.test(content) ||
    /LOCKOUT_DURATION_MINUTES/.test(content);
}

function detectDbVariable(content) {
  const destructMatch = content.match(/(?:const|let|var)\s+\{\s*(pool|db|client|query)\s*\}\s*=\s*require\(/i);
  if (destructMatch) return destructMatch[1];
  const poolMatch = content.match(/(?:const|let|var)\s+(pool|db|client)\s*=\s*(?:new\s+(?:Pool|Client|Database)|require\()/i);
  if (poolMatch) return poolMatch[1];
  const exportMatch = content.match(/(?:const|let|var)\s+(\w+)\s*=\s*require\(['"][^'"]*(?:database|db)[^'"]*['"]\)/i);
  if (exportMatch) return exportMatch[1];
  return 'db';
}

function detectParamStyle(content) {
  if (/\$\d/.test(content)) return 'postgres';
  return 'sqlite';
}

function detectApiStyle(content) {
  if (/\.prepare\s*\(/.test(content)) return 'native';
  return 'wrapper';
}

function detectIndent(line) {
  const m = line.match(/^(\s*)/);
  return m ? m[1] : '  ';
}

function findMiddlewareDir(authFile, targetDir) {
  const authDir = path.dirname(authFile);
  // Prefer sibling middleware/ next to routes/
  const sibling = path.join(authDir, '..', 'middleware');
  if (fs.existsSync(sibling) && fs.statSync(sibling).isDirectory()) {
    return sibling;
  }
  // Common locations
  const candidates = [
    path.join(targetDir, 'backend', 'middleware'),
    path.join(targetDir, 'middleware'),
    path.join(targetDir, 'src', 'middleware')
  ];
  for (const c of candidates) {
    if (fs.existsSync(c) && fs.statSync(c).isDirectory()) return c;
  }
  // Create secureauth folder next to auth routes
  const secureauthDir = path.join(authDir, '..', 'secureauth');
  fs.mkdirSync(secureauthDir, { recursive: true });
  return secureauthDir;
}

function relativeRequirePath(fromFile, toFile) {
  let rel = path.relative(path.dirname(fromFile), toFile).replace(/\\/g, '/');
  if (!rel.startsWith('.')) rel = './' + rel;
  return rel.replace(/\.js$/, '');
}

/**
 * Standalone lockout helper that works with better-sqlite3 (.prepare)
 * or wrapper APIs (.query returning { rows }).
 */
function generateLockoutModule(apiStyle, paramStyle) {
  const isNative = apiStyle === 'native';
  const isPg = paramStyle === 'postgres';

  if (isNative) {
    return `/**
 * SecureAuth — Account Lockout
 * Auto-generated by SecureAuth CLI. Protects login against brute-force attacks.
 */
'use strict';

function createAccountLockout(db, options = {}) {
  const maxAttempts = options.maxAttempts || parseInt(process.env.MAX_FAILED_ATTEMPTS, 10) || 5;
  const durationMinutes = options.durationMinutes || parseInt(process.env.LOCKOUT_DURATION_MINUTES, 10) || 30;

  function check(user) {
    if (!user || !user.locked_until) return;
    const lockedUntil = new Date(user.locked_until);
    if (lockedUntil > new Date()) {
      const minutesLeft = Math.ceil((lockedUntil - new Date()) / 60000);
      const err = new Error(
        'Account locked due to too many failed attempts. Try again in ' + minutesLeft + ' minute(s).'
      );
      err.statusCode = 423;
      throw err;
    }
    // Lock expired — clear counters
    db.prepare(
      'UPDATE users SET failed_login_attempts = 0, locked_until = NULL, last_failed_login = NULL WHERE id = ?'
    ).run(user.id);
    user.failed_login_attempts = 0;
    user.locked_until = null;
  }

  function recordFailure(user) {
    db.prepare(
      'UPDATE users SET failed_login_attempts = failed_login_attempts + 1, last_failed_login = ? WHERE id = ?'
    ).run(new Date().toISOString(), user.id);

    const row = db.prepare('SELECT failed_login_attempts FROM users WHERE id = ?').get(user.id);
    const failedAttempts = row ? row.failed_login_attempts : 1;
    const remaining = Math.max(0, maxAttempts - failedAttempts);

    if (failedAttempts >= maxAttempts) {
      const lockedUntil = new Date();
      lockedUntil.setMinutes(lockedUntil.getMinutes() + durationMinutes);
      db.prepare('UPDATE users SET locked_until = ? WHERE id = ?').run(lockedUntil.toISOString(), user.id);
      return {
        locked: true,
        failedAttempts,
        remaining: 0,
        message:
          'Account locked due to ' +
          maxAttempts +
          ' failed attempts. Try again in ' +
          durationMinutes +
          ' minutes.'
      };
    }

    return {
      locked: false,
      failedAttempts,
      remaining,
      message:
        'Invalid credentials. ' + remaining + ' attempt(s) remaining before account lockout.'
    };
  }

  function reset(user) {
    if (!user || user.id == null) return;
    db.prepare(
      'UPDATE users SET failed_login_attempts = 0, locked_until = NULL, last_failed_login = NULL WHERE id = ?'
    ).run(user.id);
  }

  return { check, recordFailure, reset, maxAttempts, durationMinutes };
}

module.exports = { createAccountLockout };
`;
  }

  // Wrapper / postgres style (.query)
  const p1 = isPg ? '$1' : '?';
  const p2 = isPg ? '$2' : '?';
  const awaitKw = isPg ? 'await ' : '';
  const asyncKw = isPg ? 'async ' : '';

  return `/**
 * SecureAuth — Account Lockout
 * Auto-generated by SecureAuth CLI. Protects login against brute-force attacks.
 */
'use strict';

function createAccountLockout(db, options = {}) {
  const maxAttempts = options.maxAttempts || parseInt(process.env.MAX_FAILED_ATTEMPTS, 10) || 5;
  const durationMinutes = options.durationMinutes || parseInt(process.env.LOCKOUT_DURATION_MINUTES, 10) || 30;

  ${asyncKw}function check(user) {
    if (!user || !user.locked_until) return;
    const lockedUntil = new Date(user.locked_until);
    if (lockedUntil > new Date()) {
      const minutesLeft = Math.ceil((lockedUntil - new Date()) / 60000);
      const err = new Error(
        'Account locked due to too many failed attempts. Try again in ' + minutesLeft + ' minute(s).'
      );
      err.statusCode = 423;
      throw err;
    }
    ${awaitKw}db.query(
      'UPDATE users SET failed_login_attempts = 0, locked_until = NULL, last_failed_login = NULL WHERE id = ${p1}',
      [user.id]
    );
    user.failed_login_attempts = 0;
    user.locked_until = null;
  }

  ${asyncKw}function recordFailure(user) {
    ${awaitKw}db.query(
      'UPDATE users SET failed_login_attempts = failed_login_attempts + 1, last_failed_login = ${p1} WHERE id = ${p2}',
      [new Date().toISOString(), user.id]
    );
    const failedResult = ${awaitKw}db.query(
      'SELECT failed_login_attempts FROM users WHERE id = ${p1}',
      [user.id]
    );
    const failedAttempts = failedResult.rows && failedResult.rows[0]
      ? failedResult.rows[0].failed_login_attempts
      : 1;
    const remaining = Math.max(0, maxAttempts - failedAttempts);

    if (failedAttempts >= maxAttempts) {
      const lockedUntil = new Date();
      lockedUntil.setMinutes(lockedUntil.getMinutes() + durationMinutes);
      ${awaitKw}db.query('UPDATE users SET locked_until = ${p1} WHERE id = ${p2}', [
        lockedUntil.toISOString(),
        user.id
      ]);
      return {
        locked: true,
        failedAttempts,
        remaining: 0,
        message:
          'Account locked due to ' +
          maxAttempts +
          ' failed attempts. Try again in ' +
          durationMinutes +
          ' minutes.'
      };
    }

    return {
      locked: false,
      failedAttempts,
      remaining,
      message:
        'Invalid credentials. ' + remaining + ' attempt(s) remaining before account lockout.'
    };
  }

  ${asyncKw}function reset(user) {
    if (!user || user.id == null) return;
    ${awaitKw}db.query(
      'UPDATE users SET failed_login_attempts = 0, locked_until = NULL, last_failed_login = NULL WHERE id = ${p1}',
      [user.id]
    );
  }

  return { check, recordFailure, reset, maxAttempts, durationMinutes };
}

module.exports = { createAccountLockout };
`;
}

function writeLockoutModule(targetDir, authFile, apiStyle, paramStyle) {
  const middlewareDir = findMiddlewareDir(authFile, targetDir);
  const modulePath = path.join(middlewareDir, 'accountLockout.js');

  if (fs.existsSync(modulePath) && fs.readFileSync(modulePath, 'utf-8').includes('createAccountLockout')) {
    logger.info(`Lockout module already exists: ${path.relative(targetDir, modulePath)}`);
    return modulePath;
  }

  fs.mkdirSync(path.dirname(modulePath), { recursive: true });
  fs.writeFileSync(modulePath, generateLockoutModule(apiStyle, paramStyle), 'utf-8');
  logger.success(`Created ${path.relative(targetDir, modulePath)}`);
  return modulePath;
}

function patchAuthRoute(authFile, modulePath, dbVar, paramStyle) {
  let content = fs.readFileSync(authFile, 'utf-8');
  if (isAlreadyPatched(content)) {
    logger.info('Auth route already has lockout protection — skipping code patch');
    return { content, modified: false, alreadyPatched: true };
  }

  const requirePath = relativeRequirePath(authFile, modulePath);
  const isPg = paramStyle === 'postgres';
  const awaitCheck = isPg ? 'await ' : '';
  const awaitRecord = isPg ? 'await ' : '';
  const awaitReset = isPg ? 'await ' : '';

  // 1) Insert require + lockout factory after last require
  const requireLine = `const { createAccountLockout } = require('${requirePath}');\nconst accountLockout = createAccountLockout(${dbVar});\n`;
  const requireRegex = /(?:const|let|var)\s+[\w{}\s,]+\s*=\s*require\([^)]+\);?/g;
  let lastRequire = null;
  let m;
  while ((m = requireRegex.exec(content)) !== null) {
    lastRequire = m;
  }
  if (lastRequire) {
    const insertPos = lastRequire.index + lastRequire[0].length;
    content = content.slice(0, insertPos) + '\n' + requireLine + content.slice(insertPos);
  } else {
    content = requireLine + '\n' + content;
  }

  // 2) After user is found (before password compare): check lockout
  const comparePatterns = [
    /(?:const|let|var)\s+is(?:Valid|PasswordValid)\s*=\s*await\s+bcrypt\.compare\s*\(/,
    /(?:const|let|var)\s+is(?:Valid|PasswordValid)\s*=\s*bcrypt\.compareSync\s*\(/,
    /(?:const|let|var)\s+is(?:Valid|PasswordValid)\s*=\s*await\s+bcryptjs\.compare\s*\(/,
    /(?:const|let|var)\s+is(?:Valid|PasswordValid)\s*=\s*bcryptjs\.compareSync\s*\(/,
    /(?:const|let|var)\s+match(?:es)?\s*=\s*await\s+bcrypt\.compare\s*\(/,
    /(?:const|let|var)\s+match(?:es)?\s*=\s*bcrypt\.compareSync\s*\(/,
    /if\s*\(\s*!(?:await\s+)?bcrypt\.compare(?:Sync)?\s*\(/,
    /if\s*\(\s*!(?:await\s+)?bcryptjs\.compare(?:Sync)?\s*\(/
  ];

  let compareMatch = null;
  for (const p of comparePatterns) {
    const found = content.match(p);
    if (found) {
      compareMatch = found;
      break;
    }
  }

  if (!compareMatch) {
    logger.warn('Could not find password comparison in auth route — partial install');
    fs.writeFileSync(authFile, content, 'utf-8');
    return { content, modified: true, partial: true };
  }

  const lineStart = content.lastIndexOf('\n', compareMatch.index) + 1;
  const indent = detectIndent(content.slice(lineStart, compareMatch.index + 1));
  const lockoutCheck = [
    `${indent}try {`,
    `${indent}  ${awaitCheck}accountLockout.check(user);`,
    `${indent}} catch (lockErr) {`,
    `${indent}  return res.status(lockErr.statusCode || 423).json({`,
    `${indent}    error: 'Account locked',`,
    `${indent}    message: lockErr.message`,
    `${indent}  });`,
    `${indent}}`,
    ``,
    ``
  ].join('\n');

  content = content.slice(0, lineStart) + lockoutCheck + content.slice(lineStart);

  // 3) On invalid password: record failure + lockout / remaining attempts
  const invalidPatterns = [
    /if\s*\(\s*!is(?:Valid|PasswordValid)\s*\)/,
    /if\s*\(\s*!match(?:es)?\s*\)/,
    /if\s*\(\s*is(?:Valid|PasswordValid)\s*===\s*false\s*\)/
  ];

  let invalidMatch = null;
  for (const p of invalidPatterns) {
    const found = content.match(p);
    if (found) {
      invalidMatch = found;
      break;
    }
  }

  if (invalidMatch) {
    const blockStart = content.indexOf('{', invalidMatch.index);
    if (blockStart !== -1) {
      const afterBrace = content.slice(blockStart + 1);
      // Derive body indent from the if-line (more reliable than scanning after inserts)
      const ifLineStart = content.lastIndexOf('\n', invalidMatch.index) + 1;
      const ifLine = content.slice(ifLineStart, content.indexOf('\n', invalidMatch.index));
      const ifIndent = detectIndent(ifLine);
      // Prefer indent of the original return statement if present
      const returnLineMatch = afterBrace.match(/\n([ \t]*)return\s+res\.status\(40[13]\)/);
      const retIndent = returnLineMatch ? returnLineMatch[1] : ifIndent + '  ';
      const innerIndent = retIndent + '  ';

      // Find first return res.status(40x) inside the invalid-password block
      const returnMatch = afterBrace.match(/\breturn\s+res\.status\(40[13]\)/);
      if (returnMatch) {
        // Replace from the start of the return line so we don't double-indent
        const returnAbs = blockStart + 1 + returnMatch.index;
        const returnLineStart = content.lastIndexOf('\n', returnAbs) + 1;
        const rest = content.slice(returnAbs);
        const stmtMatch = rest.match(/^return\s+res\.status\(40[13]\)[\s\S]*?;/);
        if (stmtMatch) {
          const replacement = [
            `${retIndent}const failure = ${awaitRecord}accountLockout.recordFailure(user);`,
            `${retIndent}if (failure.locked) {`,
            `${innerIndent}return res.status(423).json({`,
            `${innerIndent}  error: 'Account locked',`,
            `${innerIndent}  message: failure.message`,
            `${innerIndent}});`,
            `${retIndent}}`,
            `${retIndent}return res.status(401).json({`,
            `${innerIndent}error: 'Invalid credentials',`,
            `${innerIndent}message: failure.message,`,
            `${innerIndent}remainingAttempts: failure.remaining`,
            `${retIndent}});`
          ].join('\n');
          content =
            content.slice(0, returnLineStart) +
            replacement +
            content.slice(returnAbs + stmtMatch[0].length);
        }
      }
    }
  } else {
    logger.warn('Could not find invalid-password branch — failure counting not wired');
  }

  // 4) On successful login: reset counters (before success response)
  const afterInvalid = content;
  // Look for session assignment or success response after password validation
  const successPatterns = [
    /req\.session\.user\s*=/,
    /\breturn\s+res\.status\(200\)\s*\.\s*json\(/,
    /\breturn\s+res\.json\(/,
    /\bres\.status\(200\)\s*\.\s*json\(/,
    /\bres\.json\(\s*\{\s*message:\s*['"]Login successful/
  ];

  // Only search after the last invalid-password handling (roughly after compare)
  const compareAgain = content.indexOf('accountLockout.check');
  const searchFrom = compareAgain !== -1 ? compareAgain : 0;
  const tail = content.slice(searchFrom);

  let successIdx = -1;
  let successAbs = -1;
  for (const p of successPatterns) {
    const found = tail.match(p);
    if (found && (successIdx === -1 || found.index < successIdx)) {
      // Skip if this is inside the failure branch (remainingAttempts)
      const abs = searchFrom + found.index;
      const window = content.slice(Math.max(0, abs - 200), abs);
      if (/remainingAttempts|Account locked|recordFailure/.test(window)) continue;
      successIdx = found.index;
      successAbs = abs;
    }
  }

  if (successAbs !== -1) {
    const lineStartSuccess = content.lastIndexOf('\n', successAbs) + 1;
    const successIndent = detectIndent(content.slice(lineStartSuccess, successAbs));
    // Avoid double-insert
    if (!content.slice(lineStartSuccess - 80, lineStartSuccess).includes('accountLockout.reset')) {
      const resetLine = `${successIndent}accountLockout.reset(user);\n`;
      // For postgres async
      const resetCode = isPg
        ? `${successIndent}${awaitReset}accountLockout.reset(user);\n`
        : resetLine;
      content = content.slice(0, lineStartSuccess) + resetCode + content.slice(lineStartSuccess);
    }
  } else {
    logger.warn('Could not find success path — lockout counters may not reset on login');
  }

  fs.writeFileSync(authFile, content, 'utf-8');
  return { content, modified: true, alreadyPatched: false };
}

function generateMigrationSql(dbType) {
  if (dbType === 'postgres') {
    return `-- SecureAuth: Add account lockout columns
ALTER TABLE users ADD COLUMN IF NOT EXISTS failed_login_attempts INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locked_until TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_failed_login TIMESTAMPTZ;
`;
  }
  // SQLite: IF NOT EXISTS for ADD COLUMN needs SQLite 3.35+; also provide plain ALTERs
  return `-- SecureAuth: Add account lockout columns (SQLite)
-- Run each statement; ignore "duplicate column" errors if columns already exist.
ALTER TABLE users ADD COLUMN failed_login_attempts INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN locked_until TEXT;
ALTER TABLE users ADD COLUMN last_failed_login TEXT;
`;
}

function writeMigration(targetDir, dbType) {
  const fileName = 'migration_lockout.sql';
  // Prefer backend/ if it exists
  const backendDir = path.join(targetDir, 'backend');
  const filePath = fs.existsSync(backendDir)
    ? path.join(backendDir, fileName)
    : path.join(targetDir, fileName);

  if (fs.existsSync(filePath)) {
    logger.warn(`${path.relative(targetDir, filePath)} already exists — skipping`);
    return filePath;
  }

  fs.writeFileSync(filePath, generateMigrationSql(dbType), 'utf-8');
  logger.success(`Created ${path.relative(targetDir, filePath)}`);
  return filePath;
}

const SCHEMA_FILE_CANDIDATES = [
  'initDatabase.js', 'init-db.js', 'init_db.js', 'initDatabase.ts',
  'database.js', 'db.js', 'schema.js', 'models.js',
  'database/init.js', 'database/setup.js', 'database/schema.js',
  'database/db.js', 'database/index.js',
  'db/init.js', 'db/setup.js', 'db/schema.js', 'db/index.js',
  'src/database.js', 'src/db.js', 'src/schema.js',
  'src/database/init.js', 'src/database/setup.js',
  'backend/database.js', 'backend/db.js',
  'backend/config/database.js',
  'backend/database/init.js', 'backend/database/setup.js',
  'models/User.js', 'models/user.js', 'models/userModel.js',
  'src/models/User.js', 'src/models/user.js', 'src/models/userModel.js'
];

const SCHEMA_NESTED_CANDIDATES = [
  ['database', 'schema.sql'],
  ['db', 'schema.sql'],
  ['migrations', '001_init.sql'],
  ['migrations', 'create_users.sql'],
  ['src', 'database', 'schema.sql'],
  ['prisma', 'schema.prisma']
];

function findSchemaFile(targetDir) {
  for (const name of SCHEMA_FILE_CANDIDATES) {
    const p = path.join(targetDir, name);
    if (fs.existsSync(p)) return p;
  }
  for (const parts of SCHEMA_NESTED_CANDIDATES) {
    const p = path.join(targetDir, ...parts);
    if (fs.existsSync(p)) return p;
  }
  const entry = findEntryPoint(targetDir);
  if (entry) {
    const content = fs.readFileSync(entry, 'utf-8');
    const schemaRequire = content.match(/require\(['"](\.?\.?\/[^'"]*(?:database|db|schema|initDatabase|init)[^'"]*)['"]\)/i);
    if (schemaRequire) {
      const base = path.dirname(entry);
      let schemaPath = schemaRequire[1].replace(/\.js$/, '');
      for (const ext of ['', '.js', '.ts']) {
        const full = path.resolve(base, schemaPath + ext);
        if (fs.existsSync(full) && fs.statSync(full).isFile()) return full;
      }
    }
  }
  return null;
}

function isSchemaAlreadyPatched(content) {
  return /failed_login_attempts/.test(content);
}

function detectSchemaStyle(content) {
  if (/\.exec\s*\(`[\s\S]*CREATE\s+TABLE/i.test(content) || /\.exec\s*\([\s\S]*CREATE\s+TABLE/i.test(content)) {
    return 'sqlite-exec';
  }
  if (/CREATE\s+TABLE/i.test(content)) return 'sql';
  if (/knex\.schema|createTable\s*\(/i.test(content)) return 'knex';
  if (/\.init\s*\(|\.define\s*\(/i.test(content) && /DataTypes|sequelize/i.test(content)) return 'sequelize';
  if (/model\s*\(\s*['"]users['"]/i.test(content)) return 'mongoose';
  return 'unknown';
}

function generateLockoutColumnsForSchema(dbType) {
  if (dbType === 'postgres') {
    return `        failed_login_attempts INTEGER DEFAULT 0,
        locked_until TIMESTAMPTZ,
        last_failed_login TIMESTAMPTZ`;
  }
  return `        failed_login_attempts INTEGER DEFAULT 0,
        locked_until TEXT,
        last_failed_login TEXT`;
}

function patchSqlInJs(content, dbType) {
  // Match CREATE TABLE users (...) inside template literal or string
  const createTableRegex =
    /(CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?users\s*\()([\s\S]*?)(\n\s*\))/i;
  const match = content.match(createTableRegex);
  if (!match) return { content, modified: false };

  const cols = match[2];
  if (/failed_login_attempts/.test(cols)) {
    return { content, modified: false };
  }

  // Insert before the closing paren of the column list
  const colDef = generateLockoutColumnsForSchema(dbType);
  // Ensure trailing comma on last existing column line
  let body = cols.replace(/\s*$/, '');
  if (!body.trimEnd().endsWith(',')) {
    body = body.trimEnd() + ',';
  }
  const patchedTable = match[1] + body + '\n' + colDef + match[3];
  return {
    content: content.replace(match[0], patchedTable),
    modified: true
  };
}

function patchRawSql(content, dbType) {
  return patchSqlInJs(content, dbType);
}

function patchKnexSchema(content, dbType) {
  const knexRegex =
    /createTable\s*\(\s*['"]users['"]\s*,\s*(?:function\s*\(\s*table\s*\)|\(\s*table\s*\)|\(\s*t\s*\)|\(\s*b\s*\)\s*=>|table\s*=>)/i;
  const match = content.match(knexRegex);
  if (!match) return { content, modified: false };

  const afterMatch = content.slice(match.index + match[0].length);
  const closingRegex = /\}\s*\)/;
  const closingMatch = afterMatch.match(closingRegex);
  if (!closingMatch) return { content, modified: false };

  const insertPos = match.index + match[0].length + closingMatch.index;
  const colDef =
    dbType === 'postgres'
      ? `\n    table.integer('failed_login_attempts').defaultTo(0);\n    table.timestamp('locked_until');\n    table.timestamp('last_failed_login');`
      : `\n    table.integer('failed_login_attempts').defaultTo(0);\n    table.string('locked_until');\n    table.string('last_failed_login');`;

  return {
    content: content.slice(0, insertPos) + colDef + '\n  ' + content.slice(insertPos),
    modified: true
  };
}

function patchSequelizeModel(content, dbType) {
  const initRegex = /((?:\.init|\.define)\s*\([^)]*\{[\s\S]*?)(\}\s*,)/;
  const match = content.match(initRegex);
  if (!match) return { content, modified: false };

  const colDef =
    dbType === 'postgres'
      ? `\n    failed_login_attempts: { type: DataTypes.INTEGER, defaultValue: 0 },\n    locked_until: DataTypes.DATE,\n    last_failed_login: DataTypes.DATE,`
      : `\n    failed_login_attempts: { type: DataTypes.INTEGER, defaultValue: 0 },\n    locked_until: DataTypes.TEXT,\n    last_failed_login: DataTypes.TEXT,`;

  return {
    content: content.replace(match[0], match[1] + colDef + '\n  ' + match[2]),
    modified: true
  };
}

function findSqliteDbFile(targetDir) {
  const candidates = [
    path.join(targetDir, 'cavendish.db'),
    path.join(targetDir, 'database.db'),
    path.join(targetDir, 'app.db'),
    path.join(targetDir, 'data.db'),
    path.join(targetDir, 'sqlite.db'),
    path.join(targetDir, 'secureauth.db'),
    path.join(targetDir, 'backend', 'database.db'),
    path.join(targetDir, 'backend', 'cavendish.db'),
    path.join(targetDir, 'src', 'database.db')
  ];
  for (const p of candidates) {
    if (fs.existsSync(p)) return p;
  }

  // Scan common dirs for *.db
  const scanDirs = [targetDir, path.join(targetDir, 'backend'), path.join(targetDir, 'database'), path.join(targetDir, 'data')];
  for (const dir of scanDirs) {
    if (!fs.existsSync(dir)) continue;
    try {
      for (const f of fs.readdirSync(dir)) {
        if (f.endsWith('.db') && !f.includes('-shm') && !f.includes('-wal')) {
          return path.join(dir, f);
        }
      }
    } catch {}
  }
  return null;
}

function loadBetterSqlite3(targetDir) {
  // Prefer the target project's better-sqlite3 (critical when CLI is run via npx from cache)
  try {
    const resolved = require.resolve('better-sqlite3', { paths: [targetDir] });
    return require(resolved);
  } catch {}
  try {
    return require('better-sqlite3');
  } catch {}
  return null;
}

function migrateExistingDb(targetDir, dbType) {
  if (dbType !== 'sqlite') {
    logger.info('Automatic live migration is only supported for SQLite');
    logger.info('Run migration_lockout.sql manually for PostgreSQL/MySQL');
    return false;
  }

  const dbPath = findSqliteDbFile(targetDir);
  if (!dbPath) {
    logger.info('No existing SQLite database found — columns will be added when the schema runs');
    return false;
  }

  const Database = loadBetterSqlite3(targetDir);
  if (!Database) {
    logger.warn('better-sqlite3 not available — skipping live database migration');
    logger.info('Install better-sqlite3, then re-run init, or apply migration_lockout.sql');
    return false;
  }

  const columns = [
    { name: 'failed_login_attempts', sql: 'INTEGER DEFAULT 0' },
    { name: 'locked_until', sql: 'TEXT' },
    { name: 'last_failed_login', sql: 'TEXT' }
  ];

  let db;
  try {
    db = new Database(dbPath);
    // Ensure users table exists
    const table = db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='users'").get();
    if (!table) {
      logger.warn('No users table found in database — skip live migration');
      return false;
    }

    const existing = new Set(
      db.prepare('PRAGMA table_info(users)').all().map((c) => c.name)
    );

    let added = 0;
    for (const col of columns) {
      if (existing.has(col.name)) continue;
      try {
        db.exec(`ALTER TABLE users ADD COLUMN ${col.name} ${col.sql}`);
        added++;
      } catch (e) {
        if (!/duplicate column/i.test(e.message)) throw e;
      }
    }

    if (added > 0) {
      logger.success(
        `Added ${added} lockout column(s) to ${path.relative(targetDir, dbPath)}`
      );
    } else {
      logger.info('Database already has all lockout columns');
    }
    return true;
  } catch (e) {
    logger.warn(`Could not migrate existing database: ${e.message}`);
    logger.info('You may need to run migration_lockout.sql manually');
    return false;
  } finally {
    if (db) db.close();
  }
}

function patchSchemaFile(targetDir, dbType) {
  const schemaFile = findSchemaFile(targetDir);
  if (!schemaFile) {
    logger.info('No schema file found — generating migration SQL instead');
    writeMigration(targetDir, dbType);
    migrateExistingDb(targetDir, dbType);
    return null;
  }

  // Skip pure connection modules that only open the DB (no CREATE TABLE)
  let content = fs.readFileSync(schemaFile, 'utf-8');
  if (!/CREATE\s+TABLE/i.test(content) && path.basename(schemaFile) === 'database.js') {
    // Try initDatabase next
    const initPath = path.join(targetDir, 'initDatabase.js');
    if (fs.existsSync(initPath)) {
      return patchSchemaFileWithPath(targetDir, dbType, initPath);
    }
  }

  return patchSchemaFileWithPath(targetDir, dbType, schemaFile);
}

function patchSchemaFileWithPath(targetDir, dbType, schemaFile) {
  let content = fs.readFileSync(schemaFile, 'utf-8');

  if (isSchemaAlreadyPatched(content)) {
    logger.info(`Schema already has lockout columns: ${path.relative(targetDir, schemaFile)}`);
    migrateExistingDb(targetDir, dbType);
    writeMigration(targetDir, dbType);
    return null;
  }

  // Only patch files that define a users table
  if (!/CREATE\s+TABLE/i.test(content) && !/createTable\s*\(/i.test(content) && !/DataTypes/i.test(content)) {
    logger.info(`${path.relative(targetDir, schemaFile)} has no users schema — generating migration SQL`);
    writeMigration(targetDir, dbType);
    migrateExistingDb(targetDir, dbType);
    return null;
  }

  const schemaStyle = detectSchemaStyle(content);
  logger.info(`Found schema file: ${path.relative(targetDir, schemaFile)} (style: ${schemaStyle})`);

  let result;
  switch (schemaStyle) {
    case 'sqlite-exec':
      result = patchSqlInJs(content, dbType);
      break;
    case 'sql':
      result = patchRawSql(content, dbType);
      break;
    case 'knex':
      result = patchKnexSchema(content, dbType);
      break;
    case 'sequelize':
      result = patchSequelizeModel(content, dbType);
      break;
    default:
      logger.warn(`Unknown schema style — generating migration SQL instead`);
      writeMigration(targetDir, dbType);
      migrateExistingDb(targetDir, dbType);
      return null;
  }

  if (!result.modified) {
    logger.warn('Could not auto-patch schema — generating migration SQL instead');
    writeMigration(targetDir, dbType);
    migrateExistingDb(targetDir, dbType);
    return null;
  }

  fs.writeFileSync(schemaFile, result.content, 'utf-8');
  logger.success(`Patched ${path.relative(targetDir, schemaFile)} with lockout columns`);
  writeMigration(targetDir, dbType);
  migrateExistingDb(targetDir, dbType);
  return null;
}

/**
 * Main entry: patch an existing Express app with account lockout.
 */
function patchExisting(targetDir, answers) {
  const hasLockout = answers.features && answers.features.includes('accountLockout');
  if (!hasLockout) {
    logger.info('Account lockout not selected — skipping patcher');
    return { patched: false };
  }

  const authFile = findAuthRouteFile(targetDir);
  if (!authFile) {
    logger.warn('Could not find existing auth/login route file — lockout not patched');
    logger.info('Expected paths like routes/auth.js or backend/routes/auth.js');
    return { patched: false };
  }

  logger.info(`Found auth route: ${path.relative(targetDir, authFile)}`);

  const dbType = detectDatabaseType(targetDir);
  let content = fs.readFileSync(authFile, 'utf-8');
  const paramStyle = detectParamStyle(content);
  const apiStyle = detectApiStyle(content);
  const dbVar = detectDbVariable(content);

  logger.info(
    `Database: ${dbType}, params: ${paramStyle}, API: ${apiStyle}, DB var: \`${dbVar}\``
  );

  // Write reusable lockout module
  const modulePath = writeLockoutModule(targetDir, authFile, apiStyle, paramStyle);

  // Wire module into login
  const result = patchAuthRoute(authFile, modulePath, dbVar, paramStyle);
  if (result.modified && !result.alreadyPatched) {
    logger.success(`Patched ${path.relative(targetDir, authFile)} with account lockout`);
  }

  // Schema + live DB
  patchSchemaFile(targetDir, dbType);

  logger.info('Lockout env defaults (also written to .env when possible):');
  logger.info('  MAX_FAILED_ATTEMPTS=5');
  logger.info('  LOCKOUT_DURATION_MINUTES=30');

  return {
    patched: true,
    authFile,
    modulePath,
    alreadyPatched: !!result.alreadyPatched,
    dbType
  };
}

module.exports = {
  patchExisting,
  findEntryPoint,
  findAuthRouteFile,
  findSchemaFile,
  detectSchemaStyle,
  detectDatabaseType,
  detectDbVariable,
  detectParamStyle,
  detectApiStyle,
  isAlreadyPatched,
  isSchemaAlreadyPatched,
  writeMigration,
  patchSchemaFile,
  findSqliteDbFile,
  migrateExistingDb,
  generateLockoutModule,
  writeLockoutModule,
  patchAuthRoute
};
